# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for yarn
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

    ignore:
        # Ignore all expo modules (need manual update).
        # Ignore react and react-native (need manual update)
      - dependency-name: "react"
        #ignore sub dependencies
      - dependency-name: "jmespath"


